baseURL = 'https://netotz.github.io/'
defaultContentLanguage = 'en'
languageCode = 'en'
enableEmoji = true
enableGitInfo = true

title = 'void?'
theme = 'gokarna'

[params]
    author = 'Ernesto Ortiz'
    GitHubUser = 'netotz'
    footer = ''
    avatarURL = "/null.png"
    description = 'Writings of programming and everything else'
    metaKeywords = ['blog', 'personal', 'hugo', 'github-pages', 'programming', 'journal', 'programming blog', 'essays', 'computer science', 'technology blog']
    showPostsOnHomePage = 'recent'
    accentColor = "#ffc33c"
    customHeadHTML = """
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/site.webmanifest">
    
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.css" integrity="sha384-MlJdn/WNKDGXveldHDdyRP1R4CTHr3FeuDNfhsLPYrq2t0UBkUdK2jyTnXPEK1NQ" crossorigin="anonymous">

        <!-- The loading of KaTeX is deferred to speed up page rendering -->
        <script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/katex.min.js" integrity="sha384-VQ8d8WVFw0yHhCk5E8I86oOhv48xLpnDZx5T9GogA/Y84DcCKWXDmSDfn13bzFZY" crossorigin="anonymous"></script>

        <!-- To automatically render math in text elements, include the auto-render extension: -->
        <script defer src="https://cdn.jsdelivr.net/npm/katex@0.15.2/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"
            onload="renderMathInElement(document.body);"></script>
        
        <script>
            document.addEventListener("DOMContentLoaded", function() {
                renderMathInElement(document.body, {
                    delimiters: [
                        {left: '$$', right: '$$', display: true},
                        {left: '$', right: '$', display: false}
                    ],
                    // rendering keys, e.g.:
                    throwOnError : false
                });
            });
        </script>
    """

[menu]
    [[menu.main]]
        identifier = 'posts'
        url = '/posts/'
        pre = '<span data-feather="book-open"></span>'
        name = 'Posts'
        weight = 1
    [[menu.main]]
        identifier = 'tags'
        url = '/tags/'
        pre = '<span data-feather="tag"></span>'
        name = 'Tags'
        weight = 2
    [[menu.main]]
        identifier = 'github'
        url = 'https://github.com/netotz'
        pre = '<span data-feather="github"></span>'
        weight = 3
    [[menu.main]]
        identifier = 'linkedin'
        url = 'https://www.linkedin.com/in/netotz/'
        pre = '<span data-feather="linkedin"></span>'
        weight = 4
    [[menu.main]]
        identifier = 'twitter'
        url = 'https://twitter.com/netotz'
        pre = '<span data-feather="twitter"></span>'
        weight = 5
