baseURL = 'https://netotz.github.io/'
defaultContentLanguage = 'en'
languageCode = 'en'
enableEmoji = true
enableGitInfo = true

staticDir = ['images']

title = 'void?'
theme = 'gokarna'

[params]
    author = 'Ernesto Ortiz'
    GitHubUser = 'netotz'
    footer = ''
    avatarURL = "/null.png"
    description = 'Writings of programming and everything else'
    metaKeywords = ['blog', 'personal', 'hugo', 'github-pages', 'programming', 'journal']
    showPostsOnHomePage = 'recent'
    accentColor = "#ffc33c"
    customHeadHTML = """
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.css" integrity="sha384-6LkG2wmY8FK9E0vU9OOr8UvLwsaqUg9SETfpq4uTCN1agNe8HRdE9ABlk+fVx6gZ" crossorigin="anonymous">

        <!-- The loading of KaTeX is deferred to speed up page rendering -->
        <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.js" integrity="sha384-31El76TwmbHj4rF9DyLsygbq6xoIobG0W+jqXim+a3dU9W53tdH3A/ngRPxOzzaB" crossorigin="anonymous"></script>

        <!-- To automatically render math in text elements, include the auto-render extension: -->
        <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous"
            onload="renderMathInElement(document.body);"></script>
    """

[menu]
    [[menu.main]]
        identifier = 'posts'
        url = '/posts/'
        pre = '<span data-feather="book-open"></span>'
        name = 'Posts'
        weight = 1
    [[menu.main]]
        identifier = 'tags'
        url = '/tags/'
        pre = '<span data-feather="tag"></span>'
        name = 'Tags'
        weight = 2
    [[menu.main]]
        identifier = 'github'
        url = 'https://github.com/netotz'
        pre = '<span data-feather="github"></span>'
        weight = 3
    [[menu.main]]
        identifier = 'linkedin'
        url = 'https://www.linkedin.com/in/netotz/'
        pre = '<span data-feather="linkedin"></span>'
        weight = 4
    [[menu.main]]
        identifier = 'twitter'
        url = 'https://twitter.com/netotz'
        pre = '<span data-feather="twitter"></span>'
        weight = 5
